#PBS -N PreprocessJob
#PBS -l nodes=1:ppn=1         
#PBS -l mem=20GB               
#PBS -q una-new                  
#PBS -M mscoleri@hamilton.edu  
#PBS -m bea                    
#PBS -j oe                     
#PBS -l walltime=72:30:00      
#PBS -r y

echo "Job started on"
date

cd cs330_transportation_networks

module load --module name here--

python PreprocessingFiles/Beijing_preprocessing.py

echo "Job ended at "
date
