#PBS -N PreprocessJob
#PBS -l nodes=1:ppn=1         
#PBS -l mem=20GB               
#PBS -q una-new                  
#PBS -M mscoleri@hamilton.edu  
#PBS -m bea                    
#PBS -j oe                     
#PBS -l walltime=72:30:00      
#PBS -r y

echo "Job started on $(hostname) at $(date)"

cd $PBS_O_WORKDIR/cs330_transportation_networks

module load python/3.11

python PreprocessingFiles/WashingtonDC_preprocessing.py

echo "Job ended at $(date)"
